### ISSUE TITLE
Workflow nvc-build is failing

### ISSUE THREAD

**Issue by echoi** [GeoFLAC/DynEarthSol#1]
@chaseshyu the nvc-build workflow is failing. Please make this workflow pass again.
I tried a few different potential fixes but none worked. 🥲

**Comment by chaseshyu** [comment]
@echoi, I want to debug by installation of nvidia-cuda-toolkit but the storage space for action is not enough. So I try to delete logs of previous tests and use smaller nvhpc-23-9. However, Action still cannot finish the installation. Do you have any idea to overcome this problem?

**Comment by echoi** [comment]
Sorry, it's not clear to me... Let's at least start looking into the settings for the action.

**Comment by echoi** [comment]
Sounds like the default container's disk space is insufficient. We need a larger runner (i.e., a container configured for a larger disk space) but we need to be a paying organization.

BTW, I found 24.7 downloaded and installed. Also, the building DES2D and 3D failed not because of disk space but because of an unrecognized library. Is this really a disk space issue?

**Comment by tan2** [comment]
Eunseo,

Thanks for spending time debugging the problem.
Is it possible to postpone the issue for a few months? Chase is writing his
dissertation and I would like it to finish before September. He needs to
concentrate on it.


Eunseo Choi ***@***.***> 於 2024年8月8日 週四 01:23 寫道：

**Comment by echoi** [comment]
Not a problem! @chaseshyu , I'll disable the nvcc workflow for now. Good luck with the defense!

**Comment by echoi** [comment]
Closing
